[auth]
site_url = 'http://localhost:5173'
additional_redirect_urls = ['http://localhost:5173/auth/callback']

[auth.external.google]
enabled = true
client_id = "env(AUTH_GOOGLE_ID)"
secret = "env(AUTH_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[auth.email.smtp]
host = "env(SMTP_HOST)"
port = "env(SMTP_PORT)"
user = "env(SMTP_USER)"
pass = "env(SMTP_PASS)"
sender_name = "env(SMTP_SENDER_NAME)"
admin_email = "env(SMTP_ADMIN_EMAIL)"

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100