[auth]
site_url = 'http://localhost:5173'
additional_redirect_urls = ['http://localhost:5173/auth/callback']

[auth.external.google]
enabled = true
client_id = "env(AUTH_GOOGLE_ID)"
secret = "env(AUTH_GOOGLE_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[auth.email.smtp]
host = "***REMOVED***"        # Or your mail server
port = ***REMOVED***
user = "***REMOVED***"
pass = "***REMOVED***"
sender_name = "***REMOVED***"
admin_email = "***REMOVED***"
# sender = "***REMOVED***"

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100